os: osx
language: objective-c
osx_image: xcode10.2
podfile: ./Podfile
xcode_workspace: ./RxEnumKit.xcworkspace
xcode_scheme: RxEnumKit
xcode_destination: platform=iOS Simulator,OS=11.4,name=iPhone X

before_install:
    - pod repo update

after_success:
    - bash <(curl -s https://codecov.io/bash)
